baseURL = "https://digijo.netlify.com/"
languageCode = "en-us"
title = "DigiJo - Belfast's Leading Marketing and Web Design Freelancer"

[params]
author = "DigiJo"
keywords = ["Digital Marketing", "Web Design", "Branding"]
avatar = "img/header-image.jpg"
dateform = "Jan 2, 2006"
lang = "en"
footertext = "written by DigiJo_"
googleAnalytics = ""
typeformid = "u6nTL7" # Required
typeformuser = "myuser" # Optional
typeformwidth = "100%" # Optional
typeformheight = "800px" # Optional
about = """
I'm not in the marketing industry to serve people, I'm in the people industry to serve great digital marketing. As an award winning digital marketer from beautiful Belfast, I help local businesses reach their true potential. Before you know it, you'll be attracting and converting leads like you never thought possible.
"""

[params.social]
linkedin      = ""
twitter       = ""
github        = ""

[[params.info]]
label = "Certified"
value = "Google Specialist"

[[params.infogd]]
label = "Certified"
value = "Adobe Masterclass"

[[params.projects]]
name = "Seven Technologies Group"
desc = "At Seven Technologies, I delivered a website that was, secure, super fast, and SEO-optimised. The design of the website is clean and impactful to represent the sector 7TG operate in."
img = "img/homepage/testimonials/7tg.jpg"
link = "www.7techgroup.com"

[[params.projects]]
name = "TM3"
desc = "At TM3 I co-ordinated with Eyekiller to design a beautiful, responsive website that was fully focused on converting visitors to leads - and it worked! SEO was a major focus with the TM3 website. Moving domain and keeping SEO juice was imperative. Thankfully, I managed the job perfectly, with the new domain authority jumping from 0 - 35 in 8 months. Icing on this beautiful cake, the website now ranks top of Google (#1!) for their prime keyword - Physio Software"
img = "img/homepage/testimonials/tm3.jpg"
link = "www.tm3pm.com/"

[[params.projects]]
name = "KQ Barbering"
desc = "Kristopher came to DigiJo for help with branding. DigiJo designed Kristopher a new logo, which represented the company's edge and style."
img = "img/coverrun.png"
