baseURL = "https://www.budibase.com/"
languageCode = "en-uk"
title = "All-in-one SaaS Builder For Rapid Development | Budibase"
theme = "budibase"
enableEmoji = "true"

copyright = "This work is licensed and owned by Budibase"


[params]
keywords = ["SaaS Applications", "SaaS builder", "Application builder"]
description = "Budibase is a modern SaaS builder for building, managing and hosting SaaS applications. Budibase eliminates repetition and dramatically reduces development time. Check it out."
dateform = "Jan 2, 2006"
lang = "en"
googleAnalytics = ""

[author]
  name = "Joseph Johnston"


[params.publisher]
    name = "Budibase"

   [params.publisher.logo]
      url = "/img/logo/budibase-logo-small.png"
      width = 127
      height = 40

  [params.logo]
    url = "/img/logo/budibase-logo-small.png"
    width = 127
    height = 40

  [params.image]
    url = "/img/logo/budibase-logo.png"
    width = 800
    height = 600