baseURL = "https://www.budibase.com/"
languageCode = "en-uk"
title = "Budibase - No code platform | Open Source | Custom Software"
theme = "budibase"
enableEmoji = "true"

copyright = "This work is licensed and owned by Budibase"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
keywords = ["No code platform", "Custom software", "Web application builder"]
description = "Budibase is a modern, open source no code platform for designing, building and deploying custom software. Budibase eliminates coding and allows you to build web applications in minutes. Check it out."
dateform = "Jan 2, 2006"
lang = "en"

[author]
  name = "Joseph Johnston"


[params.publisher]
    name = "Budibase"

  [params.publisher.logo]
      url = "/budibase-logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "/budibase-logo.png"
    width = 127
    height = 40

  [params.image]
    url = "/budibase-logo.png"
    width = 800
    height = 600
